### ISSUE TITLE
LDFile.SaveAllVariables

### ISSUE THREAD

**Issue by 65001** [litdev1/LitDev#2] opened 2016-10-14 21:17 UTC
Hello LitDev again , currently LDFile.SaveAllVariables works in most cases. However in [DBM Line 958](https://github.com/65001/DBM/blob/Dev/DB%20Manager.sb#L958) it only displays the following text :

> _ccb System.Threading.ContextCallback

The issue may only be reproducible in complex code bases so you may have to:
1. Download [DBM](https://github.com/65001/DBM/tree/Dev) 
2. Delete the settings file in the Assets folder 
3. Run "DB Manager.exe" 
4. Click Settings
5. Click Stack Trace
6. Navigate to $InstallDirectory\Assets\Debug.txt 

Any explanation would he helpful , Thanks in advance @litdev1 .
(Also thank you for making this dll for the Small Basic Community )

**Comment by litdev1** [comment] 2016-10-14 22:12
Hi,

Tricky to diagnose in 1700 lines of code with no debugger!

My first guess would be that SaveAllVariables fails when called from an event thread (rather than the main UI thread), which somehow is the case when settings file is deleted.  If this fits with your understanding of how your code runs then please post.

I haven't confirmed this hunch (UI v Event thread) - I will test this hypothesis in a simple test case.

**Comment by litdev1** [comment] 2016-10-14 22:31
Test case below shows that SaveAllVariables works for first (+"X") version and not for the one in Timer event thread with a similar message to the one you got (just a different event thread type message).

So now fairly confident this may be the issue - not a whole lot I can fix for this.  Thanks for reporting.

# 

test = "Hello World"
Timer.Interval = 1000
Timer.Tick = OnTick

LDFile.SaveAllVariables(File.GetSettingsFilePath()+"X")

Sub OnTick
  Timer.Pause()
  GraphicsWindow.BackgroundColor = "Red"
  LDFile.SaveAllVariables(File.GetSettingsFilePath())
EndSub

#

**Comment by 65001** [comment] 2016-10-14 22:31
The UI vs Event thread thing is plausible within the grand scheme of my code .
There is a puedo debugger within the application , you can turn it on under the Settings Editor : Debug Mode .

Stack Trace also aids... I agree though instrumenting that code would take forever .

**Comment by 65001** [comment] 2016-10-14 22:37
Would it be an option to give a list/ Array of initialized variables that would avoid this problem ?

**Comment by litdev1** [comment] 2016-10-14 22:46
The problem is that the reflection stack trace and variables is based on the current thread.  
Not sure that I could get the UI thread for its stack trace from an event thread.

So I would recommend calling LDFile.SaveAllVariables only from the main UI thread i.e. from inside a game/message loop actioned by a flag set in an event, or otherwise outside an event or subroutines called from an event.

**Comment by 65001** [comment] 2016-10-15 00:14
Ah okay , Thank you

**Closed as completed** 2016-10-15 00:30 UTC
Labels: question
